### ISSUE TITLE
Edits for graphics

### ISSUE THREAD

**Issue by squirrelsquirrel78** [spec-journalism/ivy-coronavirus-response#6]
Also:
- Suggestions for colors?

**Comment by pukelly** [comment]
Again these are small things (and I am very nitpicky I'm sorry lol). Feel free to ignore what I suggest tho- I trust y'alls's judgement.

- March 8/15 aren’t labeled on the Columbia graphic. Is this intentional?
- The school graphics use “virtual classes” and the small timeline uses “online classes” - can we choose one for consistency.
- The move-out deadline is noted on the Penn graphic but not for any of the other schools.
- Can we add “as of this date” to the march 31 label for the mobile version of the Cornell graphic.
- Can we line up the left side of the school graphic annotations.

And just FYI- in the original graphics, the annotations were intentionally organized in two columns to differentiate between incidents and responses. It doesn't really matter and I think it looks fine like this, but yeah.

Also the colors look fine! If you really want to change the first graphic colors, you could make them less bright/bold to match the subdued color of the rest of the graphics.

**Comment by raeedahw** [comment]
**Lead-in color suggestions**
China #40bf80
U.S #D13838
Italy (maybe) #F89E99
SK #44A6E0

**FIX THE TITLE. PLEASE.**

Also, this could just be me but, **spring break extended is getting cut off** on Columbia graph
![image](https://user-images.githubusercontent.com/47710664/79081053-e0db9d00-7ce7-11ea-8446-1922b63f9831.png)

ALSO, I think we should somehow **color code**/establish the red and pink color coding early on.

**Comment by raeedahw** [comment]
**The only Copy edits** (Hong and I don't see these problems, but @jsonkao pls double check)
![image](https://user-images.githubusercontent.com/47710664/79093500-72680080-7d22-11ea-9f8a-e14a5781de2d.png)

**Comment by raeedahw** [comment]
@jsonkao for first graf "In the wake of the COVID-19..." is it possible to have that on it's own, at the center of a white page and we can indicate to user to scroll into the interactive? It's weird that it's just there at the top.

Also. I would just like to say that @HongSenDu liked my font more!
<img width="997" alt="Messages Image(1923503606)" src="https://user-images.githubusercontent.com/47710664/79093875-9f68e300-7d23-11ea-860c-6476b24da759.png">
